services:
  - type: web
    name: code-sensei-backend
    repo: https://github.com/ishikajais27/code_sensei
    rootDirectory: backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
